include build.properties
include ../docker.mk

EXTRA_ARGS = --build-arg GOSU_VERSION=$(GOSU_VERSION) --build-arg GOSU_CHECKSUM=$(GOSU_CHECKSUM) \
			 --build-arg POSTGESQL_VERSION=$(POSTGESQL_VERSION) --build-arg POSTGRESQL_CHECKSUM=$(POSTGRSQL_CHECKSUM)




