include build.properties
include ../docker.mk

EXTRA_ARGS = --build-arg GOSU_VERSION=$(GOSU_VERSION) --build-arg GOSU_CHECKSUM=$(GOSU_CHECKSUM) \
			 --build-arg POSTGRESQL_VERSION=$(POSTGRESQL_VERSION) --build-arg POSTGRESQL_CHECKSUM=$(POSTGRESQL_CHECKSUM)




