---
name: 'Build Docker Images'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to Quay.io
        uses: docker/login-action@v2
        if: ${{ secrets.QUAYIO_ENABLED == 'true' }}
        with:
          registry: 'quay.io'
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}

      - name: Build docker image
        env:
          DOCKER_REGISTRIES: ${{ secrets.DOCKER_REGISTRIES }}
        run: |
          for DOCKER_REGISTRY in DOCKER_REGISTRIES; do
            DOCKER_REGISTRY="docker.io/${{ secrets.DOCKERHUB_REPOSITORY }}" make release-all
          done


